FROM tensorflow/tensorflow:2.18.0-gpu
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg \
	&& apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*
WORKDIR /app
COPY requirements-base.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --ignore-installed blinker==1.8.2 && \
    pip install --no-cache-dir -r requirements-base.txt
COPY media/ ./media/
COPY fonts/ ./fonts/
COPY pages/ ./pages/
COPY detector.py Image_Detection.py draw_utils.py .
EXPOSE 8501
CMD ["streamlit", "run", "--server.showEmailPrompt=False", "Image_Detection.py", "--server.port=8501", "--server.address=0.0.0.0"]
